import { Platform, StyleSheet } from 'react-native';

export const colors = {
  background: '#F8F6F2',
  paper: '#FFFFFF',
  ink: '#302B32',
  muted: '#756F76',
  line: '#EAE5E2',
  plum: '#775368',
  plumDark: '#56394B',
  rose: '#F1D9DD',
  roseSoft: '#FAEFF0',
  roseInk: '#92495D',
  sage: '#EAF0E9',
  sageInk: '#4D6955',
  sand: '#F0EAE1',
  soft: '#F4F1EE',
  error: '#A43C46',
};
export const serif = Platform.select({ web: 'Georgia, serif', ios: 'Georgia', default: 'serif' });
export const common = StyleSheet.create({
  row: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  between: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  wrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  title: { fontFamily: serif, color: colors.ink, fontSize: 32, lineHeight: 40 },
  heading: { fontFamily: serif, color: colors.ink, fontSize: 24, lineHeight: 32 },
  label: { color: colors.ink, fontSize: 14, fontWeight: '600', lineHeight: 22 },
  body: { color: colors.muted, fontSize: 14, lineHeight: 22 },
  small: { color: colors.muted, fontSize: 12, lineHeight: 19 },
  eyebrow: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1.8,
    lineHeight: 18,
  },
  card: {
    backgroundColor: colors.paper,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 24,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 13,
    fontSize: 15,
    lineHeight: 22,
    color: colors.ink,
    backgroundColor: colors.paper,
    minHeight: 48,
  },
  error: { color: colors.error, fontSize: 13, lineHeight: 20 },
});
